services:
  postgres:
    image: postgres:16.4
    container_name: meteogo_weather_collector_service_postgres
    environment:
      POSTGRES_DB: "meteogo-weather-collector-service-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
        - "5432:5432"
