global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'weather-collector-service'
    static_configs:
      - targets: ['host.docker.internal:2112']

# rate(kafka_send_duration_ms_sum[5m])/rate(kafka_send_duration_ms_count[5m])
