version: '3'

vars:
  APP_NAME: weather_collector_service

tasks:
  run:
    cmds:
      - go run ./cmd/{{.APP_NAME}}/main.go
    silent: false

  test:
    cmds:
      - go test -v -cover ./...
    silent: false
